version: '3'

services:
  webapp:
    image: registry.gitlab.worldline.tech/wl-football-league/wl-football-league-webapp:latest
    links:
      - api
    ports:
      - "${WEBAPP_PORT:-9090}:80"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
  api:
    image: registry.gitlab.worldline.tech/wl-football-league/wl-football-league-api:latest
    links:
      - db
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:mysql://db:3306/wlceligue?autoReconnect=true&useSSL=false
      DB_USER: root
      DB_PW: root
      DB_DRIVER: com.mysql.jdbc.Driver
      SITE_URL: ${SITE_URL:-http://localhost:9090}
      MAIL_HOST: ${MAIL_HOST:-relay-smtp.priv.atos.fr}
      MAIL_DEST:
  db:
    image: mysql:5.7
    volumes:
      - "./.data/db:/var/lib/mysql"
      - "./data:/docker-entrypoint-initdb.d"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
